[package]
name = "file-organizer"
version = "2.0.0"
edition = "2024"

[dependencies]
gpui = "0.2.2"
gpui-component = "0.4.0"
anyhow = "1.0"
notify = "8.2.0"
crossbeam-channel = "0.5.15"
async-channel = "2.5.0"

[profile.dev]
split-debuginfo = "unpacked"
debug = 0 
strip = true
